In [3]:
#np.array

import numpy as np

a=np.array([1,2,3])      #vector
print(a)

[1 2 3]


In [ ]:
# 2d and 3D

b=np.array([[1,2,3],[5,7,8]])
                                  # matrix
print(b)

[[1 2 3]
 [5 7 8]]


In [ ]:
# 3D numpy array
c=np.array([[[1,2],[4,5]],[[3,4],[8,9]]])     #tensor
print(c)


[[[1 2]
  [4 5]]

 [[3 4]
  [8 9]]]


In [5]:
# datatype

d=np.array([1,2,3],dtype=float)
print(d)

[1. 2. 3.]


In [8]:
e=np.array([5,6,7,0,-1],dtype=bool)
print(e)

[ True  True  True False  True]


In [9]:
f=np.array([1,2,3],dtype=complex)
print(f)


[1.+0.j 2.+0.j 3.+0.j]


In [11]:
# np.arange
g=np.arange(1,11)
print(g)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
g=np.arange(1,11,2)
print(g)

[1 3 5 7 9]


In [14]:
# with reshape

h=np.arange(1,11).reshape(5,2)
print(h)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [15]:
# np.ones and np.zeros

i=np.ones((3,4))
print(i)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
j=np.zeros((3,4))
print(j)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
# np.random

k=np.random.random((3,4))
print(k)

[[0.61088007 0.0193947  0.60281329 0.19369142]
 [0.00555247 0.20294277 0.78064128 0.26154085]
 [0.9401038  0.52288735 0.23552449 0.27098461]]


In [18]:
# np.linspace
l=np.linspace(-10,10,10)
print(l)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [19]:
# identity matrix

m=np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# Array Atributes


In [21]:
a1=np.arange(10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
a2=np.arange(12,dtype=float).reshape(3,4)
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [23]:
a3=np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [24]:
# ndim --to find dimension 

a1.ndim

1

In [25]:
a2.ndim

2

In [26]:
a3.ndim

3

In [27]:
# shape

a1.shape

(10,)

In [28]:
a2.shape

(3, 4)

In [29]:
a3.shape

(2, 2, 2)

In [30]:
# size 
a3.size

8

In [31]:
a1.size

10

In [32]:
a2.size

12

In [33]:
#itemsize  how much memory acquired by array
a1.itemsize



8

In [34]:
a2.itemsize

8

In [35]:
a3.itemsize

8

In [36]:
 #dtype         retuns datatype
print(a1.dtype)
 

int64


In [37]:
print(a2.dtype)

float64


In [38]:
print(a3.dtype)

int64


In [39]:
#changing datatype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
# Array operation 

# scaler operation
# vector operation


a3=np.arange(12).reshape(3,4)
a4=np.arange(12,24).reshape(3,4)

print(a3)
print(a4)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [41]:
# scaler operation
a3*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [42]:
a3+1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
a3-4

array([[-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [44]:
a3%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [ ]:
# vector OPERATOR
a4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
a4>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [47]:
a4>25

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [48]:
a4>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a4==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a3+a4

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [52]:
a3*a4

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [53]:
a3**a4

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [54]:
  #Array function

In [62]:
a7=np.random.random((3,3))
a7=np.round(a7*100)
print(a7)


[[ 45.  10.  53.]
 [ 41.  77.  81.]
 [ 98. 100.  79.]]


In [63]:
np.max(a7)

np.float64(100.0)

In [64]:
np.min(a7)

np.float64(10.0)

In [65]:
np.sum(a7)

np.float64(584.0)

In [66]:
np.prod(a7)

np.float64(4721730018390000.0)

In [67]:
# max/min/sum/prod

#0---> col and 1 ---> row

np.max(a7,axis=0)

array([ 98., 100.,  81.])

In [68]:
np.min(a7,axis=0)

array([41., 10., 53.])

In [69]:
np.prod(a7,axis=0)

array([180810.,  77000., 339147.])

In [70]:
np.sum(a7,axis=0)

array([184., 187., 213.])

In [ ]:
# mean, median ,standard deviation 

np.mean(a7)

np.float64(64.88888888888889)

In [76]:
np.mean(a7, axis=0)

array([61.33333333, 62.33333333, 71.        ])

In [77]:
np.median(a7)

np.float64(77.0)

In [78]:
np.median(a7,axis=0)

array([45., 77., 79.])

In [80]:
np.std(a7)

np.float64(27.99779532766601)

In [81]:
np.std(a7,axis=0)

array([25.97862369, 38.17794593, 12.75408431])

In [82]:
np.var(a7)

np.float64(783.8765432098767)

In [84]:
np.var(a7,axis=0)

array([ 674.88888889, 1457.55555556,  162.66666667])

In [85]:
#trignometric function 


np.sign(a7)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
np.cos(a7)

array([[ 0.52532199, -0.83907153, -0.91828279],
       [-0.98733928, -0.03097503,  0.77668598],
       [-0.81928825,  0.86231887, -0.89597095]])

In [87]:
np.tan(a7)

array([[  1.61977519,   0.64836083,  -0.4311582 ],
       [  0.1606567 , -32.26857578,  -0.81099442],
       [  0.69985365,  -0.58721392,   0.49567753]])

In [89]:
# dot product 

a8=np.arange(12).reshape(3,4)
a9=np.arange(12,24).reshape(4,3)

print(a8)
print(a9)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [90]:
np.dot(a8,a9)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [91]:
#log and exponents 


In [92]:
np.log(a8)

C:\Users\BIBHAV KUMAR\AppData\Local\Temp\ipykernel_1668\1801271659.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a8)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [93]:
np.exp(a8)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [94]:
# round // floor// ceil

In [100]:
a10=(np.random.random((2,3))*100)
print(a10)

[[82.0411293  23.27719752 43.99039355]
 [91.8505638  75.40589099 56.92230881]]


In [101]:
np.round(a10)

array([[82., 23., 44.],
       [92., 75., 57.]])

In [102]:
np.ceil(a10)

array([[83., 24., 44.],
       [92., 76., 57.]])

In [103]:
np.floor(a10)

array([[82., 23., 43.],
       [91., 75., 56.]])

In [5]:
#indexing and slicing
a11=np.arange(10)
a12=np.arange(12).reshape(3,4)
a13=np.arange(8).reshape(2,2,2)
print(a11)
print(a12)
print(a13)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [105]:
a11

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
a11[-1]

np.int64(9)

In [107]:
a11[0]

np.int64(0)

In [108]:
a12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
a12[2,3]

np.int64(11)

In [110]:
a12[0,2]

np.int64(2)

In [111]:
a12[1,2]

np.int64(6)

In [112]:
a12[1,0]

np.int64(4)

In [113]:
print(a13)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [115]:
a13[1,0,1]

np.int64(5)

In [116]:
a13[0,1,1]

np.int64(3)

In [117]:
a13[1,1,0]

np.int64(6)

In [7]:
#Slicing 
a11[0:5:2]
 

array([0, 2, 4])

In [8]:
a12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a12[0,:]

array([0, 1, 2, 3])

In [10]:
a12[1,2]

np.int64(6)

In [11]:
a12[1,0]

np.int64(4)

In [12]:
a12[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [19]:
a12[0:2,1::]

array([[1, 2, 3],
       [5, 6, 7]])

In [18]:
a12[1,0::3]

array([4, 7])

In [13]:
a12[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a12[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [20]:
a13

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
a13=np.arange(27).reshape(3,3,3)

In [22]:
print(a13)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [31]:
a13[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [27]:
a13[1,:,1]

array([10, 13, 16])

In [28]:
a13[2,1::,1::]

array([[22, 23],
       [25, 26]])

In [23]:
a13[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [24]:
a13[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [26]:
a13[0,1,:]

array([3, 4, 5])

In [32]:
#iterating



In [36]:
a11
for i in a11:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [38]:
a12
for i in a12:
    print(i)


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a13
for i in a13:
    print(i)
    

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [40]:
# to print each element of 3d array 



In [41]:
for i in np.nditer(a13):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [42]:
 # Reshape

In [43]:
a12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
np.transpose(a12)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [45]:
a12.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [48]:
a13.ravel()    # change 3d array to 1-d array.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [49]:
a12.ravel()     # change 2d array to 1-d array 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# stacking 
# horizontal stacking

# vertical stacking 

a15=np.arange(16).reshape(4,4)
print(a15)

a16=np.arange(16,32).reshape(4,4)
print(a16)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [57]:
np.hstack((a15,a16))

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [58]:
np.vstack((a15,a16))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [59]:
# spliting
# horizontal spliting

# vertical spliting 

a15


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
np.hsplit(a15,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [66]:
np.vsplit(a15,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]